const quotes = [
  "Believe you can and you're halfway there.",
  'If you can dream it, you can achieve it.',
  'Strive not to be a success, but rather to be of value.',
  'The only way to do great work is to love what you do.',
  "I have not failed. I've just found 10,000 ways that won't work.",
  'The best way to predict your future is to create it.',
  'Success is not final, failure is not fatal: It is the courage to continue that counts.',
  'The greatest glory in living lies not in never falling, but in rising every time we fall.',
  "Your time is limited, don't waste it living someone else's life.",
  'The only person you are destined to become is the person you decide to be.',
  "Don't watch the clock; do what it does. Keep going.",
  'If you want to lift yourself up, lift up someone else.',
  'Success is not how high you have climbed, but how you make a positive difference to the world.',
  'The road to success and the road to failure are almost exactly the same.',
  'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.',
  'The greatest discovery of all time is that a person can change his future by merely changing his attitude.',
  'The only limit to our realization of tomorrow will be our doubts of today.',
  "You miss 100% of the shots you don't take.",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.",
  'Success is stumbling from failure to failure with no loss of enthusiasm.',
  'The way to get started is to quit talking and begin doing.',
  'I would rather die of passion than of boredom.',
  "Don't let yesterday take up too much of today.",
  'It does not matter how slowly you go as long as you do not stop.',
  'A winner is a dreamer who never gives up.',
  'If you want to achieve greatness, stop asking for permission.',
  'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
  'Chase the vision, not the money. The money will end up following you.',
  "The most common way people give up their power is by thinking they don't have any.",
  'The mind is everything. What you think you become.',
  'Don’t count the days, make the days count.',
  'The only time you fail is when you fall down and stay down.',
  'Your attitude determines your direction.',
  'Believe in yourself and all that you are. There is something inside you that is greater than any obstacle.',
  'The harder you work for something, the greater you’ll feel when you achieve it.',
  'Strive for progress, not perfection.',
  'Don’t watch the clock; do what it does. Keep going.',
  'In the middle of every difficulty lies opportunity.',
  'The future depends on what you do today.',
  'The only way to have a friend is to be one.',
  'Don’t let what you cannot do interfere with what you can do.',
  'Success is the sum of small efforts repeated day in and day out.',
  'Dream big and dare to fail.',
  'What you do today can improve all your tomorrows.',
  'Do what you can',
];

const getRandomQuote = () => {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
};

module.exports = {
  getRandomQuote,
};
